### ISSUE TITLE
argTypes not rendered in Storybook

### ISSUE THREAD

**Issue by mark-casias** [e0ipso/twig-storybook#1]
https://www.drupal.org/project/storybook/issues/3417859

I have a story

```
{% story icons with {
    name: "Icons",
    args: {
      theIcon: "twitter"
    }
  } %}
```

which works fine, but I would like a drop down list of a variety of icons I have. But when I use:

```
{% story icons with {
    name: "Icons",
    argTypes: {
      theIcon: {
         control: "select",
         options: ["twitter", "facebook", "oc"]
       }
    }
  } %}
```

The parameter gets set (?path=/story/a11ytalks-atoms--icons&args=theIcon:facebook") but the value is never set. Is this a limitation of twig? Or am I missing a step somewhere?

The issue is in the `StoryRenderer->getArguments()` as it only looks at the `$story->meta['args']` and never looks for $story->meta['argTypes']`.  I have addressed this and will issue a PR.

**Comment by e0ipso** [comment]
I think you are right, this is a bug. In reading https://storybook.js.org/docs/api/arg-types#argtypes it is clear that this is supported, even if the common way is to define them at the `stories` level.

**Comment by e0ipso** [comment]
Hmm, on second thought. I think you are missing the `args` section. You have declared the type of argument, but you have not declared you want to use that argument.

Try this:

```twig
{% story icons with {
    name: "Icons",
    argTypes: {
      theIcon: {
         control: "select",
         options: ["twitter", "facebook", "oc"]
       }
    },
    args: { theIcon: "twitter" }
  } %}
```

**Comment by mark-casias** [comment]
oh weird.. all the documentation I saw was `args` OR `argTypes`.. hadn't seen both used.. Let me play around with it.
